/**
 * `pnpm package` — deja el proyecto listo para arrancar de un clic en Windows.
 *
 * No empaqueta un ejecutable ni incluye la CLI: compila la interfaz y escribe
 * un lanzador. Esa es la diferencia entre "arranque de un clic" y "instalador",
 * y aca solo hace falta lo primero.
 *
 * El lanzador es un `.cmd` a proposito, no un `.exe` ni un instalador:
 *
 *  - Se lee. El usuario puede abrirlo con el bloc de notas y ver exactamente
 *    que hace un archivo que va a ejecutar en su maquina.
 *  - No hay nada que firmar, y por lo tanto ninguna advertencia de SmartScreen
 *    que enseñe a ignorar advertencias.
 *  - Repara solo el caso comun: si faltan las dependencias o la compilacion,
 *    las hace antes de arrancar.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const launcherPath = path.join(repoRoot, 'Agent Workbench.cmd');

/**
 * `call` delante de cada `pnpm`: pnpm en Windows es un `.cmd`, y sin `call` el
 * control no vuelve a este script — se ejecuta el primero y el resto del
 * archivo no corre nunca.
 *
 * En ingles, como todo lo que no es la web (hito 34, D19): lo lee quien lo abre
 * para revisarlo antes de ejecutarlo, y puede ser de cualquier lado.
 */
const LAUNCHER = `@echo off
rem Agent Workbench launcher. Generated by "pnpm package".
rem You can read all of it: it does nothing it doesn't say here.
setlocal
cd /d "%~dp0"

if not exist "node_modules" (
  echo Installing dependencies for the first time...
  call corepack enable pnpm
  call pnpm install
  if errorlevel 1 goto error
)

if not exist "packages\\web\\dist\\index.html" (
  echo Building the interface...
  call pnpm build
  if errorlevel 1 goto error
)

echo Starting Agent Workbench. Close this window or press Ctrl+C to quit.
call pnpm start
if errorlevel 1 goto error
goto fin

:error
echo.
echo Something failed. The output above says what.
pause

:fin
endlocal
`;

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    stdio: 'inherit',
    // pnpm es un .cmd en Windows: sin shell, spawn no lo encuentra.
    shell: process.platform === 'win32',
  });
  if (result.status !== 0) {
    console.error(`\nFailed: ${command} ${args.join(' ')}`);
    process.exit(result.status ?? 1);
  }
}

console.log('Building the interface...');
run('pnpm', ['build']);

if (!existsSync(path.join(repoRoot, 'packages', 'web', 'dist', 'index.html'))) {
  console.error('The build did not produce packages/web/dist/index.html.');
  process.exit(1);
}

// Con CRLF: `cmd` busca las etiquetas de `goto` por bloques, y en un archivo con
// sólo LF puede no encontrar una que cae en el borde de uno.
writeFileSync(launcherPath, LAUNCHER.replace(/\n/g, '\r\n'), 'utf8');

console.log('');
console.log('Done.');
console.log(`  Launcher   ${launcherPath}`);
console.log('  Double-click that file to start the app and open the browser.');
console.log('');
if (process.platform !== 'win32') {
  console.log('  On macOS and Linux, the equivalent is "pnpm start" in this folder.');
  console.log('');
}
